from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.database import Base


class BusinessTranslation(Base):
    """
    Localized version of the translatable Business fields.
    The default-language row is the "source of truth"; other rows are
    auto-generated by the AI translation service or manually edited.
    """
    __tablename__ = "business_translations"
    __table_args__ = (
        UniqueConstraint("business_id", "language_code", name="uq_biz_lang"),
    )

    id = Column(Integer, primary_key=True, index=True)
    business_id = Column(
        Integer, ForeignKey("businesses.id", ondelete="CASCADE"), nullable=False
    )
    language_code = Column(
        String(5), ForeignKey("languages.code"), nullable=False, index=True
    )

    # Translatable fields (mirror of Business text fields)
    name = Column(String(255), default="")
    description = Column(Text, default="")
    address = Column(String(500), default="")
    schedule = Column(Text, default="{}")  # JSON string
    extra_info = Column(Text, default="")

    # Welcome message per language
    welcome = Column(Text, default="")

    # Contact form: per-language
    privacy_url = Column(String(500), default="")
    contact_texts = Column(Text, default="{}")  # JSON overrides for widget I18N keys

    # Translation provenance
    auto_translated = Column(Boolean, default=False)
    needs_review = Column(Boolean, default=False)

    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())

    business = relationship("Business", back_populates="translations")
