from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func

from app.database import Base


class IntentTranslation(Base):
    __tablename__ = "intent_translations"
    __table_args__ = (
        UniqueConstraint("intent_id", "language_code", name="uq_intent_lang"),
    )

    id = Column(Integer, primary_key=True, index=True)
    intent_id = Column(
        Integer, ForeignKey("intents.id", ondelete="CASCADE"), nullable=False
    )
    language_code = Column(
        String(5), ForeignKey("languages.code"), nullable=False, index=True
    )

    # Localized intent content
    keywords = Column(Text, default="[]")  # JSON list of strings
    response = Column(Text, nullable=False)

    # Localized button label (URL itself lives on Intent — shared across languages,
    # supports {lang} placeholder for per-language URL variants)
    button_label = Column(String(120), default="")

    # Translation provenance
    auto_translated = Column(Boolean, default=False)  # True if generated by AI
    needs_review = Column(Boolean, default=False)     # True until admin approves

    created_at = Column(DateTime, server_default=func.now())
    updated_at = Column(DateTime, server_default=func.now(), onupdate=func.now())

    intent = relationship("Intent", back_populates="translations")
